#!/usr/bin/env bash
# Generates docker/.env for the local Supabase + app stack: a fresh
# Postgres password and JWT secret, and the anon/service_role API keys
# derived from that secret (same HS256-JWT-signed-in-bash approach as
# terraform/files/bootstrap.sh.tpl uses on the Azure VM — just without the
# Key Vault round-trip, since this never leaves your machine).
#
# Also (re)generates docker/postgresql-schema.sql — mounted by
# docker-compose.yml at /etc/postgresql.schema.sql, which the
# supabase/postgres image runs (as supabase_admin, right after its own
# migrations) specifically to set role passwords. That's the ONLY place
# that works: supabase_auth_admin/authenticator are "reserved roles" and
# reject ALTER ROLE from anyone else, at any time, including postgres
# itself — this isn't documented anywhere obvious, found the hard way by
# reading migrate.sh inside the image.
#
# Safe to re-run: if docker/.env already exists, its secrets are left
# alone (so you don't rotate them under a running stack and lock yourself
# out of already-created Postgres roles) and only the schema file — which
# doesn't exist in older checkouts — is (re)written from that existing
# password. Delete docker/.env first if you want to rotate everything.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
SCHEMA_FILE="$SCRIPT_DIR/postgresql-schema.sql"
SITE_URL="${SITE_URL:-http://localhost:8000}"

write_schema_file() {
  # $POSTGRES_PASSWORD must be set by the caller. openssl rand -hex output
  # is plain [0-9a-f], so no quoting/escaping concerns embedding it in SQL.
  cat > "$SCHEMA_FILE" <<EOF
-- Generated by docker/generate-env.sh from docker/.env's POSTGRES_PASSWORD.
-- Contains a real secret in plaintext — gitignored, never commit this file.
-- Run by the supabase/postgres image itself as supabase_admin (see
-- migrate.sh's "run any post migration script to update role passwords"
-- step) — supabase_admin isn't subject to the reserved-role protection
-- that blocks a plain ALTER ROLE on these from postgres or any exec shell.
ALTER ROLE supabase_auth_admin WITH PASSWORD '$POSTGRES_PASSWORD';
ALTER ROLE authenticator WITH PASSWORD '$POSTGRES_PASSWORD';
EOF
  chmod 600 "$SCHEMA_FILE"
  echo "Wrote $SCHEMA_FILE"
}

if [[ -f "$ENV_FILE" ]]; then
  if [[ -f "$SCHEMA_FILE" ]]; then
    echo "docker/.env and docker/postgresql-schema.sql already exist — nothing to do. Delete docker/.env first for a clean slate." >&2
    exit 1
  fi
  echo "docker/.env already exists — reusing its POSTGRES_PASSWORD, only writing the missing schema file." >&2
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  write_schema_file
  echo
  echo "Next: docker compose -f docker/docker-compose.yml --env-file docker/.env down -v"
  echo "      docker compose -f docker/docker-compose.yml --env-file docker/.env up -d"
  exit 0
fi

b64url() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }
sign_jwt() {
  local role="$1" iat exp header payload h p sig
  iat=$(date +%s)
  exp=$((iat + 315360000)) # ~10 years — a local dev credential, not a user session
  header='{"alg":"HS256","typ":"JWT"}'
  payload=$(printf '{"role":"%s","iss":"supabase","iat":%d,"exp":%d}' "$role" "$iat" "$exp")
  h=$(printf '%s' "$header" | b64url)
  p=$(printf '%s' "$payload" | b64url)
  sig=$(printf '%s.%s' "$h" "$p" | openssl dgst -sha256 -hmac "$JWT_SECRET" -binary | b64url)
  printf '%s.%s.%s' "$h" "$p" "$sig"
}

POSTGRES_PASSWORD=$(openssl rand -hex 24)
JWT_SECRET=$(openssl rand -hex 32)
ANON_KEY=$(sign_jwt anon)
SERVICE_ROLE_KEY=$(sign_jwt service_role)

cat > "$ENV_FILE" <<EOF
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
JWT_SECRET=$JWT_SECRET
ANON_KEY=$ANON_KEY
SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
SITE_URL=$SITE_URL
EOF
chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE"

write_schema_file

echo
echo "Next:"
echo "  docker compose -f docker/docker-compose.yml --env-file docker/.env up -d --build"
